<img height="100" src="https://i.postimg.cc/gjptBxF4/logo-gas-removebg-preview.png" width="250"/>

# Sensitivity Analysis - Morris
> analysis performed at : /util/SensitivityAnalysis.py

Article: <br>
Paleari, L., Movedi, E., Zoli, M., Burato, A., Cecconi, I., Errahouly, J., Pecollo, E., Sorvillo, C., & Confalonieri, R. (2021). Sensitivity analysis using Morris: Just screening or an effective ranking method?. Ecological Modelling. https://doi.org/10.1016/j.ecolmodel.2021.109648.

In [1]:
import pandas as pd
import os
from glob import glob
from warnings import filterwarnings

filterwarnings("ignore")

# Setting the path to the results folder
path_to_results = os.path.join(os.getcwd(), "output", "Sensitivity Analysis", "*.csv")
files = glob(path_to_results)

In [2]:
df = pd.read_csv(files[0], sep=",", header=0, skiprows=0)
df.head()

,parameter,mu_star,sigma,mu,point_id,cluster_id,latitude,longitude
0,AMAXTB000,5.476600e+03,3.587252e+04,5.453022e+03,101d9a64,0,40.75,111.75
1,AMAXTB014,1.728593e+05,5.061524e+05,1.640947e+05,101d9a64,0,40.75,111.75
2,AMAXTB082,1.210233e+06,2.438904e+06,1.210233e+06,101d9a64,0,40.75,111.75
3,AMAXTB200,4.213418e+05,8.909277e+05,4.213418e+05,101d9a64,0,40.75,111.75
4,TMPFTB000,0.000000e+00,0.000000e+00,0.000000e+00,101d9a64,0,40.75,111.75

In [3]:
# Creating a method to automatize .csv
def merge_csv(files):
    """
    The function reads multiple csv files, extracts location, year, and day from the file names,
    :param files: A list of paths to csv files.
    :return: A list of dataframes containing the processed data.
    """
    dataframes = []

    # Looping through all files
    for file in files:
        # Reading the csv file
        df = pd.read_csv(file, sep=",", header=0, skiprows=0)

        dataframes.append(df)

    return dataframes

# Creating a list of dataframes
dfs = merge_csv(files)

In [4]:
# Concatenating all dataframes into a single one
df_combined = pd.concat(dfs, ignore_index=True).round(2)
df_combined.head(), df_combined.tail()

(   parameter     mu_star       sigma          mu  point_id  cluster_id  \
 0  AMAXTB000     5476.60    35872.52     5453.02  101d9a64           0
 1  AMAXTB014   172859.34   506152.43   164094.71  101d9a64           0
 2  AMAXTB082  1210233.11  2438904.07  1210233.11  101d9a64           0
 3  AMAXTB200   421341.84   890927.72   421341.84  101d9a64           0
 4  TMPFTB000        0.00        0.00        0.00  101d9a64           0

    latitude  longitude
 0     40.75     111.75
 1     40.75     111.75
 2     40.75     111.75
 3     40.75     111.75
 4     40.75     111.75  ,
       parameter    mu_star       sigma         mu  point_id  cluster_id  \
 12745      TDWI  472440.68  1335579.37   19916.23  fc37a368           4
 12746    TEFFMX       0.00        0.00       0.00  fc37a368           4
 12747     TSUM1  423858.91   946027.47 -185988.24  fc37a368           4
 12748     TSUM2   72269.27   202141.44  -35319.47  fc37a368           4
 12749    TSUMEM       0.00        0.00       0.00  fc37a368           4

        latitude  longitude
 12745     24.75      83.75
 12746     24.75      83.75
 12747     24.75      83.75
 12748     24.75      83.75
 12749     24.75      83.75  )

In [5]:
# Grouping by cluster_id and parameter, then calculating the mean of mu_star and sigma
df_combined = df_combined.groupby(['cluster_id','parameter'])[['mu_star', 'sigma']].mean().sort_values(by='mu_star', ascending=False)

df_combined.reset_index(inplace=True); df_combined

     cluster_id  parameter       mu_star         sigma
0             2  AMAXTB082  2.194923e+06  3.228333e+06
1             3  TMPFTB020  1.832878e+06  2.590381e+06
2             2  TMPFTB020  1.801621e+06  2.528722e+06
3             2       TDWI  1.658979e+06  3.070620e+06
4             1  TMPFTB020  1.618191e+06  2.891327e+06
..          ...        ...           ...           ...
250           4     TBASEM  0.000000e+00  0.000000e+00
251           4     TEFFMX  0.000000e+00  0.000000e+00
252           4  TMPFTB008  0.000000e+00  0.000000e+00
253           4  TMPFTB000  0.000000e+00  0.000000e+00
254           4     TSUMEM  0.000000e+00  0.000000e+00

[255 rows x 4 columns]

# Selecting by cluster_id
for cluster in df_combined['cluster_id'].unique():
    print(f"Cluster ID: {cluster}")
    display(df_combined[df_combined['cluster_id'] == cluster])

In [ ]:
# Variables importance plot
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme(style="white", context='paper', font_scale=1.2)
for cluster in df_combined['cluster_id'].unique():
    df_cluster = df_combined[df_combined['cluster_id'] == cluster]

    plt.figure(figsize=(10, 6))
    sns.barplot(x='mu_star', y='parameter', data=df_cluster, palette='viridis')
    plt.title(f'Variable Importance for Cluster ID: {cluster}')
    plt.xlabel('Mu Star')
    plt.ylabel('Parameter')
    plt.tight_layout()
    plt.show()

In [6]:
# List of zeros mu_star parameters
for cluster in df_combined['cluster_id'].unique():
    df_cluster = df_combined[df_combined['cluster_id'] == cluster]
    zero_mu_star_params = df_cluster[df_cluster['mu_star'] == 0]['parameter'].tolist()
    print(f"Cluster ID: {cluster} - Parameters with zero mu_star: {zero_mu_star_params}")

Cluster ID: 2 - Parameters with zero mu_star: ['EFFTB000', 'EFFTB040', 'TBASEM', 'TEFFMX', 'SLATB', 'TSUMEM']
Cluster ID: 3 - Parameters with zero mu_star: ['SLATB', 'EFFTB040', 'EFFTB000', 'TEFFMX', 'TBASEM', 'TMPFTB045', 'TSUMEM']
Cluster ID: 1 - Parameters with zero mu_star: ['TSUMEM', 'EFFTB000', 'EFFTB040', 'SLATB', 'TBASEM', 'TEFFMX']
Cluster ID: 0 - Parameters with zero mu_star: ['TSUMEM', 'TBASEM', 'TEFFMX', 'EFFTB040', 'EFFTB000', 'SLATB']
Cluster ID: 4 - Parameters with zero mu_star: ['EFFTB040', 'EFFTB000', 'SLATB', 'TBASEM', 'TEFFMX', 'TMPFTB008', 'TMPFTB000', 'TSUMEM']

# Result: Variables excluded from the model otimization due to zero mu_star/importance
['EFFTB040', 'EFFTB000', 'SLATB', 'TEFFMX', 'TBASEM', 'TMPFTB000', 'TSUMEM']

In [7]:
# Parameter ranking by cluster
results = []
for cluster in df_combined['cluster_id'].unique():
    df_cluster = df_combined[(df_combined['cluster_id'] == cluster) & (df_combined['mu_star'] > 0)].copy()
    df_cluster = df_cluster.sort_values(by='mu_star', ascending=False).reset_index(drop=True)
    df_cluster['Rank'] = df_cluster.index + 1

    cluster_ranking = {
        'cluster_id': cluster,
        'ranking': df_cluster[['Rank', 'parameter', 'mu_star', 'sigma']].to_dict('records')
    }
    results.append(cluster_ranking)

results

[{'cluster_id': np.int64(2),
  'ranking': [{'Rank': 1,
    'parameter': 'AMAXTB082',
    'mu_star': 2194922.5846,
    'sigma': 3228332.713},
   {'Rank': 2,
    'parameter': 'TMPFTB020',
    'mu_star': 1801620.7136000001,
    'sigma': 2528721.7814},
   {'Rank': 3,
    'parameter': 'TDWI',
    'mu_star': 1658978.5244,
    'sigma': 3070620.4526},
   {'Rank': 4,
    'parameter': 'TMPFTB035',
    'mu_star': 1521705.55,
    'sigma': 2252239.0653999997},
   {'Rank': 5,
    'parameter': 'SLATB100',
    'mu_star': 1351036.3322,
    'sigma': 2351473.1188},
   {'Rank': 6,
    'parameter': 'SPAN',
    'mu_star': 1283945.365,
    'sigma': 2362332.0892},
   {'Rank': 7,
    'parameter': 'TSUM1',
    'mu_star': 1211753.148,
    'sigma': 2695383.83},
   {'Rank': 8,
    'parameter': 'DVSEND',
    'mu_star': 955486.6082000001,
    'sigma': 2955935.5112},
   {'Rank': 9,
    'parameter': 'AMAXTB200',
    'mu_star': 940056.5401999999,
    'sigma': 1582464.0916},
   {'Rank': 10,
    'parameter': 'DVSI',
    'mu_star': 752028.0081999999,
    'sigma': 1737585.9226},
   {'Rank': 11,
    'parameter': 'CVO',
    'mu_star': 711626.2734000001,
    'sigma': 1386631.834},
   {'Rank': 12,
    'parameter': 'SLATB064',
    'mu_star': 684641.452,
    'sigma': 1429396.2476},
   {'Rank': 13,
    'parameter': 'DLC',
    'mu_star': 580584.3486,
    'sigma': 2318383.3944},
   {'Rank': 14,
    'parameter': 'RFSETB200',
    'mu_star': 567766.5644,
    'sigma': 963402.4724},
   {'Rank': 15,
    'parameter': 'RMO',
    'mu_star': 533472.2764,
    'sigma': 1104060.8373999998},
   {'Rank': 16,
    'parameter': 'IDSL',
    'mu_star': 515408.2646,
    'sigma': 2350593.8326},
   {'Rank': 17,
    'parameter': 'RMS',
    'mu_star': 514517.8512,
    'sigma': 1002989.7946000001},
   {'Rank': 18,
    'parameter': 'SLATB029',
    'mu_star': 502326.06200000003,
    'sigma': 1050197.4042},
   {'Rank': 19,
    'parameter': 'AMAXTB014',
    'mu_star': 440477.304,
    'sigma': 1116619.612},
   {'Rank': 20,
    'parameter': 'TBASE',
    'mu_star': 413065.2428,
    'sigma': 860664.0022},
   {'Rank': 21,
    'parameter': 'RRI',
    'mu_star': 389256.1454,
    'sigma': 1224383.1095999999},
   {'Rank': 22,
    'parameter': 'RFSETB000',
    'mu_star': 362033.441,
    'sigma': 640894.5686},
   {'Rank': 23,
    'parameter': 'TSUM2',
    'mu_star': 279017.5106,
    'sigma': 731764.1020000001},
   {'Rank': 24,
    'parameter': 'SLATB000',
    'mu_star': 250808.255,
    'sigma': 866216.8286},
   {'Rank': 25,
    'parameter': 'RML',
    'mu_star': 207243.2342,
    'sigma': 352429.81159999996},
   {'Rank': 26,
    'parameter': 'RDMCR',
    'mu_star': 183036.4016,
    'sigma': 830717.4232000001},
   {'Rank': 27,
    'parameter': 'CFET',
    'mu_star': 169060.87300000002,
    'sigma': 487410.2666},
   {'Rank': 28,
    'parameter': 'CVS',
    'mu_star': 157150.113,
    'sigma': 251847.0732},
   {'Rank': 29,
    'parameter': 'SLATB021',
    'mu_star': 156772.65480000002,
    'sigma': 617829.4765999999},
   {'Rank': 30,
    'parameter': 'RDI',
    'mu_star': 154817.612,
    'sigma': 529737.3802},
   {'Rank': 31,
    'parameter': 'RMR',
    'mu_star': 128523.46960000001,
    'sigma': 252034.03579999998},
   {'Rank': 32,
    'parameter': 'RGRLAI',
    'mu_star': 121958.91140000001,
    'sigma': 675393.4631999999},
   {'Rank': 33,
    'parameter': 'CVL',
    'mu_star': 102398.17880000001,
    'sigma': 201401.3296},
   {'Rank': 34, 'parameter': 'DLO', 'mu_star': 90659.17, 'sigma': 558373.084},
   {'Rank': 35,
    'parameter': 'DEPNR',
    'mu_star': 86166.2948,
    'sigma': 236441.8164},
   {'Rank': 36,
    'parameter': 'PERDL',
    'mu_star': 85325.3708,
    'sigma': 347505.4318},
   {'Rank': 37,
    'parameter': 'IOX',
    'mu_star': 64747.4292,
    'sigma': 474073.6184},
   {'Rank': 38,
    'parameter': 'IAIRDU',
    'mu_star': 46855.3378,
    'sigma': 267651.83879999997},
   {'Rank': 39,
    'parameter': 'SLATB200',
    'mu_star': 37957.8984,
    'sigma': 77028.51860000001},
   {'Rank': 40,
    'parameter': 'AMAXTB000',
    'mu_star': 37416.847799999996,
    'sigma': 160656.6766},
   {'Rank': 41, 'parameter': 'Q10', 'mu_star': 36846.6408, 'sigma': 73943.896},
   {'Rank': 42,
    'parameter': 'CVR',
    'mu_star': 20516.0322,
    'sigma': 40042.5032},
   {'Rank': 43,
    'parameter': 'TMPFTB008',
    'mu_star': 4408.7864,
    'sigma': 11829.546999999999},
   {'Rank': 44,
    'parameter': 'TMPFTB045',
    'mu_star': 529.714,
    'sigma': 1726.885},
   {'Rank': 45,
    'parameter': 'TMPFTB000',
    'mu_star': 25.605999999999998,
    'sigma': 70.2828}]},
 {'cluster_id': np.int64(3),
  'ranking': [{'Rank': 1,
    'parameter': 'TMPFTB020',
    'mu_star': 1832877.5696,
    'sigma': 2590380.9862},
   {'Rank': 2,
    'parameter': 'AMAXTB082',
    'mu_star': 1436353.0224000001,
    'sigma': 2145708.5708},
   {'Rank': 3,
    'parameter': 'TSUM1',
    'mu_star': 1340331.5315999999,
    'sigma': 2862834.4266000004},
   {'Rank': 4,
    'parameter': 'TDWI',
    'mu_star': 1091545.5836,
    'sigma': 2252352.6868000003},
   {'Rank': 5,
    'parameter': 'DVSI',
    'mu_star': 977568.1102,
    'sigma': 2074929.31},
   {'Rank': 6,
    'parameter': 'SPAN',
    'mu_star': 773784.8854,
    'sigma': 1688141.833},
   {'Rank': 7,
    'parameter': 'SLATB100',
    'mu_star': 680176.9848000001,
    'sigma': 1255088.9928000001},
   {'Rank': 8,
    'parameter': 'SLATB064',
    'mu_star': 652790.7844,
    'sigma': 1524419.5925999999},
   {'Rank': 9,
    'parameter': 'AMAXTB200',
    'mu_star': 627281.788,
    'sigma': 1376702.6008000001},
   {'Rank': 10,
    'parameter': 'DVSEND',
    'mu_star': 582252.7324,
    'sigma': 1654150.9980000001},
   {'Rank': 11,
    'parameter': 'CVO',
    'mu_star': 552741.3574,
    'sigma': 1084489.7948},
   {'Rank': 12,
    'parameter': 'TBASE',
    'mu_star': 539048.5792,
    'sigma': 1047571.553},
   {'Rank': 13,
    'parameter': 'SLATB029',
    'mu_star': 342882.4446,
    'sigma': 861371.052},
   {'Rank': 14,
    'parameter': 'AMAXTB014',
    'mu_star': 324544.4096,
    'sigma': 845373.791},
   {'Rank': 15,
    'parameter': 'TSUM2',
    'mu_star': 300103.8916,
    'sigma': 763639.5128},
   {'Rank': 16,
    'parameter': 'DLC',
    'mu_star': 291921.9538,
    'sigma': 1452313.3462},
   {'Rank': 17,
    'parameter': 'TMPFTB035',
    'mu_star': 282484.3022,
    'sigma': 460549.8174},
   {'Rank': 18,
    'parameter': 'RMS',
    'mu_star': 270470.0532,
    'sigma': 505650.5032},
   {'Rank': 19,
    'parameter': 'RFSETB200',
    'mu_star': 268108.287,
    'sigma': 565105.2021999999},
   {'Rank': 20,
    'parameter': 'IDSL',
    'mu_star': 244745.77800000002,
    'sigma': 1172811.9438},
   {'Rank': 21,
    'parameter': 'RMO',
    'mu_star': 217344.7236,
    'sigma': 508493.1468},
   {'Rank': 22,
    'parameter': 'RFSETB000',
    'mu_star': 174245.5256,
    'sigma': 267322.1366},
   {'Rank': 23,
    'parameter': 'TMPFTB008',
    'mu_star': 171196.9866,
    'sigma': 317527.4732},
   {'Rank': 24,
    'parameter': 'SLATB000',
    'mu_star': 164888.0332,
    'sigma': 510801.53660000005},
   {'Rank': 25,
    'parameter': 'RML',
    'mu_star': 138365.1036,
    'sigma': 240303.4268},
   {'Rank': 26,
    'parameter': 'RMR',
    'mu_star': 87366.2822,
    'sigma': 163357.5592},
   {'Rank': 27,
    'parameter': 'DLO',
    'mu_star': 77147.503,
    'sigma': 472758.5214},
   {'Rank': 28,
    'parameter': 'CVS',
    'mu_star': 69724.7438,
    'sigma': 122543.1654},
   {'Rank': 29,
    'parameter': 'Q10',
    'mu_star': 69546.162,
    'sigma': 114130.3286},
   {'Rank': 30,
    'parameter': 'SLATB021',
    'mu_star': 69335.2098,
    'sigma': 230081.89760000003},
   {'Rank': 31,
    'parameter': 'RRI',
    'mu_star': 62629.3716,
    'sigma': 268311.9684},
   {'Rank': 32,
    'parameter': 'CVL',
    'mu_star': 59134.8062,
    'sigma': 122836.4854},
   {'Rank': 33,
    'parameter': 'RGRLAI',
    'mu_star': 44322.1296,
    'sigma': 262717.01879999996},
   {'Rank': 34,
    'parameter': 'SLATB200',
    'mu_star': 21348.407799999997,
    'sigma': 55911.9396},
   {'Rank': 35,
    'parameter': 'CFET',
    'mu_star': 19883.3902,
    'sigma': 101392.87400000001},
   {'Rank': 36,
    'parameter': 'AMAXTB000',
    'mu_star': 18933.550600000002,
    'sigma': 99507.4902},
   {'Rank': 37,
    'parameter': 'RDI',
    'mu_star': 16952.5582,
    'sigma': 99450.1234},
   {'Rank': 38,
    'parameter': 'DEPNR',
    'mu_star': 16829.883400000002,
    'sigma': 89348.55880000001},
   {'Rank': 39,
    'parameter': 'CVR',
    'mu_star': 11695.514799999999,
    'sigma': 25574.243599999998},
   {'Rank': 40,
    'parameter': 'RDMCR',
    'mu_star': 9884.5882,
    'sigma': 49300.664000000004},
   {'Rank': 41,
    'parameter': 'PERDL',
    'mu_star': 3245.4282000000003,
    'sigma': 18175.898},
   {'Rank': 42,
    'parameter': 'TMPFTB000',
    'mu_star': 494.6778,
    'sigma': 1500.9672},
   {'Rank': 43,
    'parameter': 'IAIRDU',
    'mu_star': 126.48479999999999,
    'sigma': 1055.0991999999999},
   {'Rank': 44, 'parameter': 'IOX', 'mu_star': 105.9408, 'sigma': 918.7542}]},
 {'cluster_id': np.int64(1),
  'ranking': [{'Rank': 1,
    'parameter': 'TMPFTB020',
    'mu_star': 1618190.5237999998,
    'sigma': 2891327.2116},
   {'Rank': 2,
    'parameter': 'AMAXTB082',
    'mu_star': 1415325.6663999998,
    'sigma': 2360715.1672},
   {'Rank': 3,
    'parameter': 'TSUM1',
    'mu_star': 1224077.0638,
    'sigma': 2743519.8758},
   {'Rank': 4,
    'parameter': 'TDWI',
    'mu_star': 1183582.3642,
    'sigma': 2335176.3252000003},
   {'Rank': 5,
    'parameter': 'SPAN',
    'mu_star': 1070230.7164,
    'sigma': 2302554.4359999998},
   {'Rank': 6,
    'parameter': 'DVSI',
    'mu_star': 976415.325,
    'sigma': 2239576.4772},
   {'Rank': 7,
    'parameter': 'SLATB100',
    'mu_star': 858194.2574,
    'sigma': 1513167.8236000002},
   {'Rank': 8,
    'parameter': 'TMPFTB035',
    'mu_star': 701871.9831999999,
    'sigma': 1192757.3624},
   {'Rank': 9,
    'parameter': 'SLATB064',
    'mu_star': 648130.7872,
    'sigma': 1435852.8756},
   {'Rank': 10,
    'parameter': 'AMAXTB200',
    'mu_star': 620781.8221999999,
    'sigma': 1155592.3388},
   {'Rank': 11,
    'parameter': 'DVSEND',
    'mu_star': 607801.3622,
    'sigma': 1934371.563},
   {'Rank': 12,
    'parameter': 'TBASE',
    'mu_star': 542511.4962,
    'sigma': 1080733.7462},
   {'Rank': 13,
    'parameter': 'IDSL',
    'mu_star': 509634.9834,
    'sigma': 2477601.3316},
   {'Rank': 14,
    'parameter': 'RRI',
    'mu_star': 484852.349,
    'sigma': 1681646.7618},
   {'Rank': 15,
    'parameter': 'CVO',
    'mu_star': 456880.29880000005,
    'sigma': 1131440.6186},
   {'Rank': 16,
    'parameter': 'SLATB029',
    'mu_star': 406315.39119999995,
    'sigma': 1078146.1262},
   {'Rank': 17,
    'parameter': 'RFSETB200',
    'mu_star': 403488.88039999997,
    'sigma': 771790.8462},
   {'Rank': 18,
    'parameter': 'RMS',
    'mu_star': 351053.218,
    'sigma': 773833.8095999999},
   {'Rank': 19,
    'parameter': 'AMAXTB014',
    'mu_star': 316771.4706,
    'sigma': 794091.5012},
   {'Rank': 20,
    'parameter': 'DLC',
    'mu_star': 302825.9098,
    'sigma': 1770407.4178},
   {'Rank': 21,
    'parameter': 'SLATB000',
    'mu_star': 250198.18300000002,
    'sigma': 792573.8672},
   {'Rank': 22,
    'parameter': 'RMO',
    'mu_star': 245144.86179999998,
    'sigma': 705706.2414},
   {'Rank': 23,
    'parameter': 'CFET',
    'mu_star': 241871.43120000002,
    'sigma': 758278.1258},
   {'Rank': 24,
    'parameter': 'RFSETB000',
    'mu_star': 219252.12,
    'sigma': 429599.7002},
   {'Rank': 25,
    'parameter': 'RDMCR',
    'mu_star': 212976.3932,
    'sigma': 879596.9042},
   {'Rank': 26,
    'parameter': 'RDI',
    'mu_star': 212268.2804,
    'sigma': 812345.0231999999},
   {'Rank': 27,
    'parameter': 'TSUM2',
    'mu_star': 183469.479,
    'sigma': 521725.2226},
   {'Rank': 28,
    'parameter': 'TMPFTB008',
    'mu_star': 171276.96,
    'sigma': 377845.83479999995},
   {'Rank': 29,
    'parameter': 'DEPNR',
    'mu_star': 147432.9904,
    'sigma': 410921.9386},
   {'Rank': 30,
    'parameter': 'RML',
    'mu_star': 143703.5662,
    'sigma': 279753.6906},
   {'Rank': 31,
    'parameter': 'SLATB021',
    'mu_star': 135942.4642,
    'sigma': 453422.21839999995},
   {'Rank': 32,
    'parameter': 'CVS',
    'mu_star': 103219.4884,
    'sigma': 227846.259},
   {'Rank': 33,
    'parameter': 'PERDL',
    'mu_star': 102566.30720000001,
    'sigma': 398685.26259999996},
   {'Rank': 34,
    'parameter': 'RMR',
    'mu_star': 94318.4416,
    'sigma': 222398.79280000002},
   {'Rank': 35,
    'parameter': 'CVL',
    'mu_star': 71158.1744,
    'sigma': 162449.7042},
   {'Rank': 36,
    'parameter': 'RGRLAI',
    'mu_star': 57521.8866,
    'sigma': 313137.155},
   {'Rank': 37,
    'parameter': 'DLO',
    'mu_star': 43313.3822,
    'sigma': 365990.72740000003},
   {'Rank': 38,
    'parameter': 'Q10',
    'mu_star': 37089.7922,
    'sigma': 78498.9892},
   {'Rank': 39,
    'parameter': 'SLATB200',
    'mu_star': 29667.0352,
    'sigma': 78789.5274},
   {'Rank': 40,
    'parameter': 'CVR',
    'mu_star': 21879.790800000002,
    'sigma': 58156.8058},
   {'Rank': 41,
    'parameter': 'AMAXTB000',
    'mu_star': 21709.785,
    'sigma': 119251.68},
   {'Rank': 42,
    'parameter': 'IAIRDU',
    'mu_star': 3650.1276000000003,
    'sigma': 24037.3846},
   {'Rank': 43,
    'parameter': 'IOX',
    'mu_star': 1348.1601999999998,
    'sigma': 10747.701000000001},
   {'Rank': 44,
    'parameter': 'TMPFTB045',
    'mu_star': 373.4636,
    'sigma': 1058.6864},
   {'Rank': 45,
    'parameter': 'TMPFTB000',
    'mu_star': 109.1022,
    'sigma': 364.92080000000004}]},
 {'cluster_id': np.int64(0),
  'ranking': [{'Rank': 1,
    'parameter': 'TMPFTB020',
    'mu_star': 1586057.045,
    'sigma': 2393659.8832},
   {'Rank': 2,
    'parameter': 'AMAXTB082',
    'mu_star': 1319182.5398000001,
    'sigma': 2273951.1769999997},
   {'Rank': 3,
    'parameter': 'TSUM1',
    'mu_star': 1287359.882,
    'sigma': 2745925.4825999998},
   {'Rank': 4,
    'parameter': 'TDWI',
    'mu_star': 979578.767,
    'sigma': 1788546.6462},
   {'Rank': 5,
    'parameter': 'DVSI',
    'mu_star': 875737.1081999999,
    'sigma': 1760232.0225999998},
   {'Rank': 6,
    'parameter': 'SPAN',
    'mu_star': 780055.6356,
    'sigma': 1748928.7275999999},
   {'Rank': 7,
    'parameter': 'DVSEND',
    'mu_star': 775217.14,
    'sigma': 3016308.9156},
   {'Rank': 8,
    'parameter': 'SLATB100',
    'mu_star': 677916.8834,
    'sigma': 1280547.2404},
   {'Rank': 9,
    'parameter': 'RRI',
    'mu_star': 592077.7538000001,
    'sigma': 2004388.2962},
   {'Rank': 10,
    'parameter': 'RDMCR',
    'mu_star': 556781.781,
    'sigma': 1961034.7859999998},
   {'Rank': 11,
    'parameter': 'TMPFTB035',
    'mu_star': 512213.8988,
    'sigma': 804594.3544},
   {'Rank': 12,
    'parameter': 'CVO',
    'mu_star': 506039.29219999997,
    'sigma': 1113581.193},
   {'Rank': 13,
    'parameter': 'AMAXTB200',
    'mu_star': 500395.653,
    'sigma': 1199906.2602},
   {'Rank': 14,
    'parameter': 'SLATB064',
    'mu_star': 489291.2232,
    'sigma': 1028251.2114},
   {'Rank': 15,
    'parameter': 'TBASE',
    'mu_star': 451621.0872,
    'sigma': 895107.6395999999},
   {'Rank': 16,
    'parameter': 'SLATB029',
    'mu_star': 351016.035,
    'sigma': 778910.8718000001},
   {'Rank': 17,
    'parameter': 'RFSETB200',
    'mu_star': 328099.99419999996,
    'sigma': 614311.4786},
   {'Rank': 18,
    'parameter': 'RMS',
    'mu_star': 281000.8714,
    'sigma': 460733.41079999995},
   {'Rank': 19,
    'parameter': 'IDSL',
    'mu_star': 273106.6394,
    'sigma': 1343432.5104},
   {'Rank': 20,
    'parameter': 'CFET',
    'mu_star': 260855.0614,
    'sigma': 718070.8004000001},
   {'Rank': 21,
    'parameter': 'RMO',
    'mu_star': 236443.3366,
    'sigma': 621542.6976},
   {'Rank': 22,
    'parameter': 'AMAXTB014',
    'mu_star': 228375.8498,
    'sigma': 719593.698},
   {'Rank': 23,
    'parameter': 'DLC',
    'mu_star': 224952.9696,
    'sigma': 1117273.274},
   {'Rank': 24,
    'parameter': 'TSUM2',
    'mu_star': 183650.78579999998,
    'sigma': 493546.9042},
   {'Rank': 25,
    'parameter': 'RFSETB000',
    'mu_star': 161609.5944,
    'sigma': 295672.38759999996},
   {'Rank': 26,
    'parameter': 'DEPNR',
    'mu_star': 158846.37900000002,
    'sigma': 408925.5808},
   {'Rank': 27,
    'parameter': 'RDI',
    'mu_star': 141158.0348,
    'sigma': 437571.411},
   {'Rank': 28,
    'parameter': 'SLATB000',
    'mu_star': 117714.18939999999,
    'sigma': 581365.5924},
   {'Rank': 29,
    'parameter': 'RML',
    'mu_star': 105051.3922,
    'sigma': 174491.08},
   {'Rank': 30,
    'parameter': 'PERDL',
    'mu_star': 96173.64439999999,
    'sigma': 368254.6026},
   {'Rank': 31,
    'parameter': 'TMPFTB008',
    'mu_star': 82610.8608,
    'sigma': 151407.2076},
   {'Rank': 32,
    'parameter': 'CVS',
    'mu_star': 80689.814,
    'sigma': 151939.4766},
   {'Rank': 33,
    'parameter': 'SLATB021',
    'mu_star': 73212.28259999999,
    'sigma': 274515.6836},
   {'Rank': 34,
    'parameter': 'CVL',
    'mu_star': 51464.9216,
    'sigma': 123381.49279999999},
   {'Rank': 35,
    'parameter': 'RMR',
    'mu_star': 48453.5588,
    'sigma': 80418.3194},
   {'Rank': 36,
    'parameter': 'RGRLAI',
    'mu_star': 42518.6266,
    'sigma': 349384.38920000003},
   {'Rank': 37,
    'parameter': 'Q10',
    'mu_star': 42486.932199999996,
    'sigma': 86802.8714},
   {'Rank': 38,
    'parameter': 'SLATB200',
    'mu_star': 29459.207400000003,
    'sigma': 99892.4958},
   {'Rank': 39,
    'parameter': 'AMAXTB000',
    'mu_star': 13407.126,
    'sigma': 92477.5674},
   {'Rank': 40,
    'parameter': 'CVR',
    'mu_star': 13292.269199999999,
    'sigma': 38757.016},
   {'Rank': 41,
    'parameter': 'DLO',
    'mu_star': 12753.753400000001,
    'sigma': 117967.5726},
   {'Rank': 42, 'parameter': 'IAIRDU', 'mu_star': 779.2564, 'sigma': 5402.059},
   {'Rank': 43,
    'parameter': 'IOX',
    'mu_star': 510.3054,
    'sigma': 3764.5047999999997},
   {'Rank': 44,
    'parameter': 'TMPFTB000',
    'mu_star': 38.058,
    'sigma': 125.65879999999999},
   {'Rank': 45,
    'parameter': 'TMPFTB045',
    'mu_star': 21.616999999999997,
    'sigma': 65.3216}]},
 {'cluster_id': np.int64(4),
  'ranking': [{'Rank': 1,
    'parameter': 'TMPFTB035',
    'mu_star': 695848.1059999999,
    'sigma': 1404796.3334000001},
   {'Rank': 2,
    'parameter': 'AMAXTB082',
    'mu_star': 584489.1732,
    'sigma': 1262596.8144},
   {'Rank': 3,
    'parameter': 'RRI',
    'mu_star': 473408.2436,
    'sigma': 1065223.2928},
   {'Rank': 4,
    'parameter': 'TSUM1',
    'mu_star': 432250.8564,
    'sigma': 1017788.4876000001},
   {'Rank': 5,
    'parameter': 'TDWI',
    'mu_star': 426727.20759999997,
    'sigma': 1130830.8782000002},
   {'Rank': 6,
    'parameter': 'DVSEND',
    'mu_star': 378798.99700000003,
    'sigma': 1303899.6542},
   {'Rank': 7,
    'parameter': 'RDI',
    'mu_star': 332740.0906,
    'sigma': 795903.1202},
   {'Rank': 8,
    'parameter': 'SPAN',
    'mu_star': 308301.55199999997,
    'sigma': 1046272.2372},
   {'Rank': 9,
    'parameter': 'DVSI',
    'mu_star': 274214.2388,
    'sigma': 613790.2938},
   {'Rank': 10,
    'parameter': 'AMAXTB200',
    'mu_star': 266986.7006,
    'sigma': 667450.687},
   {'Rank': 11,
    'parameter': 'RDMCR',
    'mu_star': 256927.5032,
    'sigma': 1064951.9648},
   {'Rank': 12,
    'parameter': 'SLATB100',
    'mu_star': 245459.51280000003,
    'sigma': 724975.9852},
   {'Rank': 13,
    'parameter': 'DLC',
    'mu_star': 192420.9932,
    'sigma': 823116.2432},
   {'Rank': 14,
    'parameter': 'TMPFTB045',
    'mu_star': 166654.296,
    'sigma': 510894.6364},
   {'Rank': 15,
    'parameter': 'SLATB064',
    'mu_star': 164467.6566,
    'sigma': 491243.4678},
   {'Rank': 16,
    'parameter': 'IDSL',
    'mu_star': 164051.3278,
    'sigma': 658833.1501999999},
   {'Rank': 17,
    'parameter': 'CFET',
    'mu_star': 162868.051,
    'sigma': 479437.2892},
   {'Rank': 18,
    'parameter': 'RFSETB200',

In [8]:
# Lista simplificada dos top parâmetros por cluster
for cluster_data in results:
    cluster_id = cluster_data['cluster_id']
    top_params = [item['parameter'] for item in cluster_data['ranking'][:44]]
    print(f"Cluster {cluster_id}: {top_params}")

Cluster 2: ['AMAXTB082', 'TMPFTB020', 'TDWI', 'TMPFTB035', 'SLATB100', 'SPAN', 'TSUM1', 'DVSEND', 'AMAXTB200', 'DVSI', 'CVO', 'SLATB064', 'DLC', 'RFSETB200', 'RMO', 'IDSL', 'RMS', 'SLATB029', 'AMAXTB014', 'TBASE', 'RRI', 'RFSETB000', 'TSUM2', 'SLATB000', 'RML', 'RDMCR', 'CFET', 'CVS', 'SLATB021', 'RDI', 'RMR', 'RGRLAI', 'CVL', 'DLO', 'DEPNR', 'PERDL', 'IOX', 'IAIRDU', 'SLATB200', 'AMAXTB000', 'Q10', 'CVR', 'TMPFTB008', 'TMPFTB045']
Cluster 3: ['TMPFTB020', 'AMAXTB082', 'TSUM1', 'TDWI', 'DVSI', 'SPAN', 'SLATB100', 'SLATB064', 'AMAXTB200', 'DVSEND', 'CVO', 'TBASE', 'SLATB029', 'AMAXTB014', 'TSUM2', 'DLC', 'TMPFTB035', 'RMS', 'RFSETB200', 'IDSL', 'RMO', 'RFSETB000', 'TMPFTB008', 'SLATB000', 'RML', 'RMR', 'DLO', 'CVS', 'Q10', 'SLATB021', 'RRI', 'CVL', 'RGRLAI', 'SLATB200', 'CFET', 'AMAXTB000', 'RDI', 'DEPNR', 'CVR', 'RDMCR', 'PERDL', 'TMPFTB000', 'IAIRDU', 'IOX']
Cluster 1: ['TMPFTB020', 'AMAXTB082', 'TSUM1', 'TDWI', 'SPAN', 'DVSI', 'SLATB100', 'TMPFTB035', 'SLATB064', 'AMAXTB200', 'DVSEND', 'TBASE', 'IDSL', 'RRI', 'CVO', 'SLATB029', 'RFSETB200', 'RMS', 'AMAXTB014', 'DLC', 'SLATB000', 'RMO', 'CFET', 'RFSETB000', 'RDMCR', 'RDI', 'TSUM2', 'TMPFTB008', 'DEPNR', 'RML', 'SLATB021', 'CVS', 'PERDL', 'RMR', 'CVL', 'RGRLAI', 'DLO', 'Q10', 'SLATB200', 'CVR', 'AMAXTB000', 'IAIRDU', 'IOX', 'TMPFTB045']
Cluster 0: ['TMPFTB020', 'AMAXTB082', 'TSUM1', 'TDWI', 'DVSI', 'SPAN', 'DVSEND', 'SLATB100', 'RRI', 'RDMCR', 'TMPFTB035', 'CVO', 'AMAXTB200', 'SLATB064', 'TBASE', 'SLATB029', 'RFSETB200', 'RMS', 'IDSL', 'CFET', 'RMO', 'AMAXTB014', 'DLC', 'TSUM2', 'RFSETB000', 'DEPNR', 'RDI', 'SLATB000', 'RML', 'PERDL', 'TMPFTB008', 'CVS', 'SLATB021', 'CVL', 'RMR', 'RGRLAI', 'Q10', 'SLATB200', 'AMAXTB000', 'CVR', 'DLO', 'IAIRDU', 'IOX', 'TMPFTB000']
Cluster 4: ['TMPFTB035', 'AMAXTB082', 'RRI', 'TSUM1', 'TDWI', 'DVSEND', 'RDI', 'SPAN', 'DVSI', 'AMAXTB200', 'RDMCR', 'SLATB100', 'DLC', 'TMPFTB045', 'SLATB064', 'IDSL', 'CFET', 'RFSETB200', 'SLATB029', 'AMAXTB014', 'SLATB000', 'RMO', 'RMS', 'CVO', 'TMPFTB020', 'DEPNR', 'DLO', 'RFSETB000', 'RML', 'TSUM2', 'SLATB021', 'IAIRDU', 'RMR', 'Q10', 'PERDL', 'TBASE', 'AMAXTB000', 'CVL', 'CVS', 'IOX', 'RGRLAI', 'CVR', 'SLATB200']

In [9]:
# del dfs, files, path_to_results

# Saving SA results
path_to_results = os.path.join(os.getcwd(), "output", "Sensitivity Analysis", "SA_result.xlsx")
df_combined.to_excel(path_to_results, index=True, header=True)